/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    'admin-users': AdminUserAuthOperations;
  };
  blocks: {};
  collections: {
    'admin-users': AdminUser;
    media: Media;
    events: Event;
    artworks: Artwork;
    participants: Participant;
    'scan-events': ScanEvent;
    'reward-entries': RewardEntry;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    'admin-users': AdminUsersSelect<false> | AdminUsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    events: EventsSelect<false> | EventsSelect<true>;
    artworks: ArtworksSelect<false> | ArtworksSelect<true>;
    participants: ParticipantsSelect<false> | ParticipantsSelect<true>;
    'scan-events': ScanEventsSelect<false> | ScanEventsSelect<true>;
    'reward-entries': RewardEntriesSelect<false> | RewardEntriesSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: ('false' | 'none' | 'null') | false | null | ('en' | 'fr') | ('en' | 'fr')[];
  globals: {
    'site-copy': SiteCopy;
  };
  globalsSelect: {
    'site-copy': SiteCopySelect<false> | SiteCopySelect<true>;
  };
  locale: 'en' | 'fr';
  widgets: {
    collections: CollectionsWidget;
  };
  user: AdminUser;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface AdminUserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "admin-users".
 */
export interface AdminUser {
  id: number;
  name?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'admin-users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  caption?: string | null;
  assetType: 'image' | 'video' | 'poster' | 'fallback';
  event?: (number | null) | Event;
  artwork?: (number | null) | Artwork;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events".
 */
export interface Event {
  id: number;
  title: string;
  slug: string;
  venueName: string;
  city: string;
  eventDate: string;
  status: 'draft' | 'active' | 'closed';
  defaultLocale: 'en' | 'fr';
  supportedLocales?:
    | {
        locale?: ('en' | 'fr') | null;
        id?: string | null;
      }[]
    | null;
  introCopy?: string | null;
  instructionsCopy?: string | null;
  completionCopy?: string | null;
  prizeCopy?: string | null;
  bonvoyCopy?: string | null;
  totalRequiredArtworks: number;
  publicProgressEnabled?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "artworks".
 */
export interface Artwork {
  id: number;
  title: string;
  slug: string;
  event: number | Event;
  theme?: string | null;
  locationLabel?: string | null;
  displayOrder: number;
  clueText?: string | null;
  brandStory?: string | null;
  completionMessage?: string | null;
  lockedImage?: (number | null) | Media;
  revealedImage?: (number | null) | Media;
  videoAsset?: (number | null) | Media;
  posterImage?: (number | null) | Media;
  isActive?: boolean | null;
  isBonvoyBonus?: boolean | null;
  /**
   * Legacy URL-style QR path. Do not use for new artwork QR codes.
   */
  qrPath?: string | null;
  /**
   * Opaque artwork QR token. Printed QR payload should be mgq:v1:{eventSlug}:{qrToken}.
   */
  qrToken: string;
  qrLabel?: string | null;
  qrIsActive?: boolean | null;
  /**
   * First-party dynamic QR slug. Printed URL can be /q/{slug}.
   */
  qrDynamicSlug?: string | null;
  /**
   * Full first-party dynamic URL printed in the QR code. Dynamically generated from NEXT_PUBLIC_APP_URL.
   */
  qrDynamicUrl?: string | null;
  /**
   * Internal destination payload. Example: mgq:v1:moxy-paris-la-villette-2026:{qrToken}. Can be changed after printing.
   */
  qrDynamicDestination?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "participants".
 */
export interface Participant {
  id: number;
  uid: string;
  event: number | Event;
  firstName: string;
  lastName?: string | null;
  displayName: string;
  email?: string | null;
  company?: string | null;
  preferredLocale?: ('en' | 'fr') | null;
  isBonvoyMember?: boolean | null;
  marketingConsent?: boolean | null;
  termsAccepted: boolean;
  registeredAt: string;
  lastActiveAt?: string | null;
  completedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "scan-events".
 */
export interface ScanEvent {
  id: number;
  event: number | Event;
  participant: number | Participant;
  artwork: number | Artwork;
  scannedAt: string;
  locale?: ('en' | 'fr') | null;
  userAgent?: string | null;
  ipHash?: string | null;
  source: 'qr' | 'manual' | 'staff_test';
  isFirstScanForArtwork?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reward-entries".
 */
export interface RewardEntry {
  id: number;
  event: number | Event;
  participant: number | Participant;
  isComplete?: boolean | null;
  completedAt?: string | null;
  standardRewardEligible?: boolean | null;
  bonvoyRewardEligible?: boolean | null;
  prizeDrawEntries?: number | null;
  rewardClaimed?: boolean | null;
  claimedAt?: string | null;
  staffNotes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'admin-users';
        value: number | AdminUser;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'events';
        value: number | Event;
      } | null)
    | ({
        relationTo: 'artworks';
        value: number | Artwork;
      } | null)
    | ({
        relationTo: 'participants';
        value: number | Participant;
      } | null)
    | ({
        relationTo: 'scan-events';
        value: number | ScanEvent;
      } | null)
    | ({
        relationTo: 'reward-entries';
        value: number | RewardEntry;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'admin-users';
    value: number | AdminUser;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'admin-users';
    value: number | AdminUser;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "admin-users_select".
 */
export interface AdminUsersSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  assetType?: T;
  event?: T;
  artwork?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events_select".
 */
export interface EventsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  venueName?: T;
  city?: T;
  eventDate?: T;
  status?: T;
  defaultLocale?: T;
  supportedLocales?:
    | T
    | {
        locale?: T;
        id?: T;
      };
  introCopy?: T;
  instructionsCopy?: T;
  completionCopy?: T;
  prizeCopy?: T;
  bonvoyCopy?: T;
  totalRequiredArtworks?: T;
  publicProgressEnabled?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "artworks_select".
 */
export interface ArtworksSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  event?: T;
  theme?: T;
  locationLabel?: T;
  displayOrder?: T;
  clueText?: T;
  brandStory?: T;
  completionMessage?: T;
  lockedImage?: T;
  revealedImage?: T;
  videoAsset?: T;
  posterImage?: T;
  isActive?: T;
  isBonvoyBonus?: T;
  qrPath?: T;
  qrToken?: T;
  qrLabel?: T;
  qrIsActive?: T;
  qrDynamicSlug?: T;
  qrDynamicUrl?: T;
  qrDynamicDestination?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "participants_select".
 */
export interface ParticipantsSelect<T extends boolean = true> {
  uid?: T;
  event?: T;
  firstName?: T;
  lastName?: T;
  displayName?: T;
  email?: T;
  company?: T;
  preferredLocale?: T;
  isBonvoyMember?: T;
  marketingConsent?: T;
  termsAccepted?: T;
  registeredAt?: T;
  lastActiveAt?: T;
  completedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "scan-events_select".
 */
export interface ScanEventsSelect<T extends boolean = true> {
  event?: T;
  participant?: T;
  artwork?: T;
  scannedAt?: T;
  locale?: T;
  userAgent?: T;
  ipHash?: T;
  source?: T;
  isFirstScanForArtwork?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reward-entries_select".
 */
export interface RewardEntriesSelect<T extends boolean = true> {
  event?: T;
  participant?: T;
  isComplete?: T;
  completedAt?: T;
  standardRewardEligible?: T;
  bonvoyRewardEligible?: T;
  prizeDrawEntries?: T;
  rewardClaimed?: T;
  claimedAt?: T;
  staffNotes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * All guest-facing interface text. Each field is localized — switch locale in the top bar to edit French. Use separate lines for multi-line text and heading rows.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-copy".
 */
export interface SiteCopy {
  id: number;
  headingArtHunter?: string | null;
  headingHowToPlay?: string | null;
  headingPixelPerfect?: string | null;
  headingRegister?: string | null;
  landingIntro?: string | null;
  landingPlayOn?: string | null;
  landingRegisterCta?: string | null;
  step1?: string | null;
  step2?: string | null;
  step3?: string | null;
  step4?: string | null;
  registerPrompt?: string | null;
  registerNamePlaceholder?: string | null;
  registerPhonePlaceholder?: string | null;
  registerEmailPlaceholder?: string | null;
  registerTerms?: string | null;
  registerTermsLink?: string | null;
  registerSubmit?: string | null;
  registerError?: string | null;
  galleryTitle?: string | null;
  galleryYouHaveFound?: string | null;
  galleryScanArtwork?: string | null;
  galleryTapToOpen?: string | null;
  completeCongrats?: string | null;
  completeGallery?: string | null;
  completeClaim?: string | null;
  completeBack?: string | null;
  navYourGallery?: string | null;
  navAccount?: string | null;
  navRegister?: string | null;
  navSignIn?: string | null;
  scannerStartLabel?: string | null;
  scannerFound?: string | null;
  scannerGoToGallery?: string | null;
  scannerUnlocked?: string | null;
  scannerOpening?: string | null;
  scannerStop?: string | null;
  scannerSaving?: string | null;
  scannerCameraDenied?: string | null;
  revealPlay?: string | null;
  revealTapForSound?: string | null;
  loginHeading?: string | null;
  loginPrompt?: string | null;
  loginEmailPlaceholder?: string | null;
  loginContinue?: string | null;
  loginNewHere?: string | null;
  loginRegisterLink?: string | null;
  loginNotFound?: string | null;
  shareCopied?: string | null;
  shareCopyHint?: string | null;
  networkError?: string | null;
  lockedArtworkAlt?: string | null;
  rewardEligible?: string | null;
  completeTitle?: string | null;
  completeVerifyNote?: string | null;
  completeViewGallery?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-copy_select".
 */
export interface SiteCopySelect<T extends boolean = true> {
  headingArtHunter?: T;
  headingHowToPlay?: T;
  headingPixelPerfect?: T;
  headingRegister?: T;
  landingIntro?: T;
  landingPlayOn?: T;
  landingRegisterCta?: T;
  step1?: T;
  step2?: T;
  step3?: T;
  step4?: T;
  registerPrompt?: T;
  registerNamePlaceholder?: T;
  registerPhonePlaceholder?: T;
  registerEmailPlaceholder?: T;
  registerTerms?: T;
  registerTermsLink?: T;
  registerSubmit?: T;
  registerError?: T;
  galleryTitle?: T;
  galleryYouHaveFound?: T;
  galleryScanArtwork?: T;
  galleryTapToOpen?: T;
  completeCongrats?: T;
  completeGallery?: T;
  completeClaim?: T;
  completeBack?: T;
  navYourGallery?: T;
  navAccount?: T;
  navRegister?: T;
  navSignIn?: T;
  scannerStartLabel?: T;
  scannerFound?: T;
  scannerGoToGallery?: T;
  scannerUnlocked?: T;
  scannerOpening?: T;
  scannerStop?: T;
  scannerSaving?: T;
  scannerCameraDenied?: T;
  revealPlay?: T;
  revealTapForSound?: T;
  loginHeading?: T;
  loginPrompt?: T;
  loginEmailPlaceholder?: T;
  loginContinue?: T;
  loginNewHere?: T;
  loginRegisterLink?: T;
  loginNotFound?: T;
  shareCopied?: T;
  shareCopyHint?: T;
  networkError?: T;
  lockedArtworkAlt?: T;
  rewardEligible?: T;
  completeTitle?: T;
  completeVerifyNote?: T;
  completeViewGallery?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}